-- MineLua Item Registry — full MCBE item list
local ItemRegistry = {}
ItemRegistry.__index = ItemRegistry

local _instance
function ItemRegistry.getInstance()
    if not _instance then
        _instance = setmetatable({}, ItemRegistry)
        _instance.items = {}
        _instance.by_name = {}
        _instance:_load()
    end
    return _instance
end

function ItemRegistry:get(id_or_name)
    if type(id_or_name) == "number" then return self.items[id_or_name] end
    local n = id_or_name:lower()
    if not n:find(":") then n = "minecraft:" .. n end
    return self.by_name[n]
end

function ItemRegistry:register(item)
    self.items[item.id] = item
    if item.name then self.by_name[item.name] = item end
end

function ItemRegistry:_load()
    local list = {
        -- ── Tools ──
        {id=256, name="minecraft:iron_shovel",        display="Iron Shovel",        stack=1,  durability=250},
        {id=257, name="minecraft:iron_pickaxe",       display="Iron Pickaxe",       stack=1,  durability=250},
        {id=258, name="minecraft:iron_axe",           display="Iron Axe",           stack=1,  durability=250},
        {id=259, name="minecraft:flint_and_steel",    display="Flint and Steel",    stack=1,  durability=64},
        {id=260, name="minecraft:apple",              display="Apple",              stack=64, food=4},
        {id=261, name="minecraft:bow",                display="Bow",                stack=1,  durability=384},
        {id=262, name="minecraft:arrow",              display="Arrow",              stack=64},
        {id=263, name="minecraft:coal",               display="Coal",               stack=64},
        {id=264, name="minecraft:diamond",            display="Diamond",            stack=64},
        {id=265, name="minecraft:iron_ingot",         display="Iron Ingot",         stack=64},
        {id=266, name="minecraft:gold_ingot",         display="Gold Ingot",         stack=64},
        {id=267, name="minecraft:iron_sword",         display="Iron Sword",         stack=1,  durability=250},
        {id=268, name="minecraft:wooden_sword",       display="Wooden Sword",       stack=1,  durability=59},
        {id=269, name="minecraft:wooden_shovel",      display="Wooden Shovel",      stack=1,  durability=59},
        {id=270, name="minecraft:wooden_pickaxe",     display="Wooden Pickaxe",     stack=1,  durability=59},
        {id=271, name="minecraft:wooden_axe",         display="Wooden Axe",         stack=1,  durability=59},
        {id=272, name="minecraft:stone_sword",        display="Stone Sword",        stack=1,  durability=131},
        {id=273, name="minecraft:stone_shovel",       display="Stone Shovel",       stack=1,  durability=131},
        {id=274, name="minecraft:stone_pickaxe",      display="Stone Pickaxe",      stack=1,  durability=131},
        {id=275, name="minecraft:stone_axe",          display="Stone Axe",          stack=1,  durability=131},
        {id=276, name="minecraft:diamond_sword",      display="Diamond Sword",      stack=1,  durability=1561},
        {id=277, name="minecraft:diamond_shovel",     display="Diamond Shovel",     stack=1,  durability=1561},
        {id=278, name="minecraft:diamond_pickaxe",    display="Diamond Pickaxe",    stack=1,  durability=1561},
        {id=279, name="minecraft:diamond_axe",        display="Diamond Axe",        stack=1,  durability=1561},
        -- ── Food ──
        {id=280, name="minecraft:stick",              display="Stick",              stack=64},
        {id=281, name="minecraft:bowl",               display="Bowl",               stack=64},
        {id=282, name="minecraft:mushroom_stew",      display="Mushroom Stew",      stack=1,  food=6},
        {id=283, name="minecraft:golden_sword",       display="Golden Sword",       stack=1,  durability=32},
        {id=284, name="minecraft:golden_shovel",      display="Golden Shovel",      stack=1,  durability=32},
        {id=285, name="minecraft:golden_pickaxe",     display="Golden Pickaxe",     stack=1,  durability=32},
        {id=286, name="minecraft:golden_axe",         display="Golden Axe",         stack=1,  durability=32},
        {id=287, name="minecraft:string",             display="String",             stack=64},
        {id=288, name="minecraft:feather",            display="Feather",            stack=64},
        {id=289, name="minecraft:gunpowder",          display="Gunpowder",          stack=64},
        {id=290, name="minecraft:wooden_hoe",         display="Wooden Hoe",         stack=1,  durability=59},
        {id=291, name="minecraft:stone_hoe",          display="Stone Hoe",          stack=1,  durability=131},
        {id=292, name="minecraft:iron_hoe",           display="Iron Hoe",           stack=1,  durability=250},
        {id=293, name="minecraft:diamond_hoe",        display="Diamond Hoe",        stack=1,  durability=1561},
        {id=294, name="minecraft:golden_hoe",         display="Golden Hoe",         stack=1,  durability=32},
        {id=295, name="minecraft:wheat_seeds",        display="Wheat Seeds",        stack=64},
        {id=296, name="minecraft:wheat",              display="Wheat",              stack=64},
        {id=297, name="minecraft:bread",              display="Bread",              stack=64, food=5},
        {id=298, name="minecraft:leather_helmet",     display="Leather Helmet",     stack=1,  durability=55,  armor=1},
        {id=299, name="minecraft:leather_chestplate", display="Leather Chestplate", stack=1,  durability=80,  armor=3},
        {id=300, name="minecraft:leather_leggings",   display="Leather Leggings",   stack=1,  durability=75,  armor=2},
        {id=301, name="minecraft:leather_boots",      display="Leather Boots",      stack=1,  durability=65,  armor=1},
        {id=302, name="minecraft:chainmail_helmet",   display="Chainmail Helmet",   stack=1,  durability=165, armor=2},
        {id=303, name="minecraft:chainmail_chestplate",display="Chainmail Chestplate",stack=1,durability=240,armor=5},
        {id=304, name="minecraft:chainmail_leggings", display="Chainmail Leggings", stack=1,  durability=225, armor=4},
        {id=305, name="minecraft:chainmail_boots",    display="Chainmail Boots",    stack=1,  durability=195, armor=1},
        {id=306, name="minecraft:iron_helmet",        display="Iron Helmet",        stack=1,  durability=165, armor=2},
        {id=307, name="minecraft:iron_chestplate",    display="Iron Chestplate",    stack=1,  durability=240, armor=6},
        {id=308, name="minecraft:iron_leggings",      display="Iron Leggings",      stack=1,  durability=225, armor=5},
        {id=309, name="minecraft:iron_boots",         display="Iron Boots",         stack=1,  durability=195, armor=2},
        {id=310, name="minecraft:diamond_helmet",     display="Diamond Helmet",     stack=1,  durability=363, armor=3},
        {id=311, name="minecraft:diamond_chestplate", display="Diamond Chestplate", stack=1,  durability=528, armor=8},
        {id=312, name="minecraft:diamond_leggings",   display="Diamond Leggings",   stack=1,  durability=495, armor=6},
        {id=313, name="minecraft:diamond_boots",      display="Diamond Boots",      stack=1,  durability=429, armor=3},
        {id=314, name="minecraft:golden_helmet",      display="Golden Helmet",      stack=1,  durability=77,  armor=2},
        {id=315, name="minecraft:golden_chestplate",  display="Golden Chestplate",  stack=1,  durability=112, armor=5},
        {id=316, name="minecraft:golden_leggings",    display="Golden Leggings",    stack=1,  durability=105, armor=3},
        {id=317, name="minecraft:golden_boots",       display="Golden Boots",       stack=1,  durability=91,  armor=1},
        {id=318, name="minecraft:flint",              display="Flint",              stack=64},
        {id=319, name="minecraft:porkchop",           display="Raw Porkchop",       stack=64, food=3},
        {id=320, name="minecraft:cooked_porkchop",    display="Cooked Porkchop",    stack=64, food=8},
        {id=321, name="minecraft:painting",           display="Painting",           stack=64},
        {id=322, name="minecraft:golden_apple",       display="Golden Apple",       stack=64, food=4},
        {id=323, name="minecraft:sign",               display="Sign",               stack=16},
        {id=324, name="minecraft:wooden_door",        display="Oak Door",           stack=64},
        {id=325, name="minecraft:bucket",             display="Bucket",             stack=16},
        {id=326, name="minecraft:water_bucket",       display="Water Bucket",       stack=1},
        {id=327, name="minecraft:lava_bucket",        display="Lava Bucket",        stack=1},
        {id=328, name="minecraft:minecart",           display="Minecart",           stack=1},
        {id=329, name="minecraft:saddle",             display="Saddle",             stack=1},
        {id=330, name="minecraft:iron_door",          display="Iron Door",          stack=64},
        {id=331, name="minecraft:redstone",           display="Redstone",           stack=64},
        {id=332, name="minecraft:snowball",           display="Snowball",           stack=16},
        {id=333, name="minecraft:boat",               display="Oak Boat",           stack=1},
        {id=334, name="minecraft:leather",            display="Leather",            stack=64},
        {id=335, name="minecraft:milk_bucket",        display="Milk Bucket",        stack=1},
        {id=336, name="minecraft:brick",              display="Brick",              stack=64},
        {id=337, name="minecraft:clay_ball",          display="Clay Ball",          stack=64},
        {id=338, name="minecraft:reeds",              display="Sugar Cane",         stack=64},
        {id=339, name="minecraft:paper",              display="Paper",              stack=64},
        {id=340, name="minecraft:book",               display="Book",               stack=64},
        {id=341, name="minecraft:slime_ball",         display="Slimeball",          stack=64},
        {id=342, name="minecraft:chest_minecart",     display="Chest Minecart",     stack=1},
        {id=343, name="minecraft:furnace_minecart",   display="Furnace Minecart",   stack=1},
        {id=344, name="minecraft:egg",                display="Egg",                stack=16},
        {id=345, name="minecraft:compass",            display="Compass",            stack=64},
        {id=346, name="minecraft:fishing_rod",        display="Fishing Rod",        stack=1,  durability=64},
        {id=347, name="minecraft:clock",              display="Clock",              stack=64},
        {id=348, name="minecraft:glowstone_dust",     display="Glowstone Dust",     stack=64},
        {id=349, name="minecraft:fish",               display="Raw Fish",           stack=64, food=2},
        {id=350, name="minecraft:cooked_fish",        display="Cooked Fish",        stack=64, food=5},
        {id=351, name="minecraft:dye",                display="Ink Sac",            stack=64},
        {id=352, name="minecraft:bone",               display="Bone",               stack=64},
        {id=353, name="minecraft:sugar",              display="Sugar",              stack=64},
        {id=354, name="minecraft:cake",               display="Cake",               stack=1},
        {id=355, name="minecraft:bed",                display="Red Bed",            stack=1},
        {id=356, name="minecraft:repeater",           display="Redstone Repeater",  stack=64},
        {id=357, name="minecraft:cookie",             display="Cookie",             stack=64, food=2},
        {id=358, name="minecraft:filled_map",         display="Map",                stack=64},
        {id=359, name="minecraft:shears",             display="Shears",             stack=1,  durability=238},
        {id=360, name="minecraft:melon",              display="Melon Slice",        stack=64, food=2},
        {id=361, name="minecraft:pumpkin_seeds",      display="Pumpkin Seeds",      stack=64},
        {id=362, name="minecraft:melon_seeds",        display="Melon Seeds",        stack=64},
        {id=363, name="minecraft:beef",               display="Raw Beef",           stack=64, food=3},
        {id=364, name="minecraft:cooked_beef",        display="Steak",              stack=64, food=8},
        {id=365, name="minecraft:chicken",            display="Raw Chicken",        stack=64, food=2},
        {id=366, name="minecraft:cooked_chicken",     display="Cooked Chicken",     stack=64, food=6},
        {id=367, name="minecraft:rotten_flesh",       display="Rotten Flesh",       stack=64, food=4},
        {id=368, name="minecraft:ender_pearl",        display="Ender Pearl",        stack=16},
        {id=369, name="minecraft:blaze_rod",          display="Blaze Rod",          stack=64},
        {id=370, name="minecraft:ghast_tear",         display="Ghast Tear",         stack=64},
        {id=371, name="minecraft:gold_nugget",        display="Gold Nugget",        stack=64},
        {id=372, name="minecraft:nether_wart",        display="Nether Wart",        stack=64},
        {id=373, name="minecraft:potion",             display="Potion",             stack=1},
        {id=374, name="minecraft:glass_bottle",       display="Glass Bottle",       stack=64},
        {id=375, name="minecraft:spider_eye",         display="Spider Eye",         stack=64, food=2},
        {id=376, name="minecraft:fermented_spider_eye",display="Fermented Spider Eye",stack=64},
        {id=377, name="minecraft:blaze_powder",       display="Blaze Powder",       stack=64},
        {id=378, name="minecraft:magma_cream",        display="Magma Cream",        stack=64},
        {id=379, name="minecraft:brewing_stand",      display="Brewing Stand",      stack=64},
        {id=380, name="minecraft:cauldron",           display="Cauldron",           stack=64},
        {id=381, name="minecraft:ender_eye",          display="Eye of Ender",       stack=64},
        {id=382, name="minecraft:speckled_melon",     display="Glistering Melon Slice",stack=64},
        {id=383, name="minecraft:spawn_egg",          display="Spawn Egg",          stack=64},
        {id=384, name="minecraft:experience_bottle",  display="Bottle o' Enchanting",stack=64},
        {id=385, name="minecraft:fire_charge",        display="Fire Charge",        stack=64},
        {id=386, name="minecraft:writable_book",      display="Book and Quill",     stack=1},
        {id=387, name="minecraft:written_book",       display="Written Book",       stack=16},
        {id=388, name="minecraft:emerald",            display="Emerald",            stack=64},
        {id=389, name="minecraft:frame",              display="Item Frame",         stack=64},
        {id=390, name="minecraft:flower_pot",         display="Flower Pot",         stack=64},
        {id=391, name="minecraft:carrot",             display="Carrot",             stack=64, food=3},
        {id=392, name="minecraft:potato",             display="Potato",             stack=64, food=1},
        {id=393, name="minecraft:baked_potato",       display="Baked Potato",       stack=64, food=5},
        {id=394, name="minecraft:poisonous_potato",   display="Poisonous Potato",   stack=64, food=2},
        {id=395, name="minecraft:map",                display="Empty Map",          stack=64},
        {id=396, name="minecraft:golden_carrot",      display="Golden Carrot",      stack=64, food=6},
        {id=397, name="minecraft:skull",              display="Skull",              stack=64},
        {id=398, name="minecraft:carrot_on_a_stick",  display="Carrot on a Stick",  stack=1,  durability=25},
        {id=399, name="minecraft:nether_star",        display="Nether Star",        stack=64},
        {id=400, name="minecraft:pumpkin_pie",        display="Pumpkin Pie",        stack=64, food=8},
        {id=401, name="minecraft:fireworks",          display="Firework Rocket",    stack=64},
        {id=402, name="minecraft:fireworkscharge",    display="Firework Star",      stack=64},
        {id=403, name="minecraft:enchanted_book",     display="Enchanted Book",     stack=1},
        {id=404, name="minecraft:comparator",         display="Redstone Comparator",stack=64},
        {id=405, name="minecraft:netherbrick",        display="Nether Brick",       stack=64},
        {id=406, name="minecraft:quartz",             display="Nether Quartz",      stack=64},
        {id=407, name="minecraft:tnt_minecart",       display="TNT Minecart",       stack=1},
        {id=408, name="minecraft:hopper_minecart",    display="Hopper Minecart",    stack=1},
        {id=409, name="minecraft:prismarine_shard",   display="Prismarine Shard",   stack=64},
        {id=410, name="minecraft:hopper",             display="Hopper",             stack=64},
        {id=411, name="minecraft:rabbit",             display="Raw Rabbit",         stack=64, food=3},
        {id=412, name="minecraft:cooked_rabbit",      display="Cooked Rabbit",      stack=64, food=5},
        {id=413, name="minecraft:rabbit_stew",        display="Rabbit Stew",        stack=1,  food=10},
        {id=414, name="minecraft:rabbit_foot",        display="Rabbit's Foot",      stack=64},
        {id=415, name="minecraft:rabbit_hide",        display="Rabbit Hide",        stack=64},
        {id=416, name="minecraft:armor_stand",        display="Armor Stand",        stack=64},
        {id=417, name="minecraft:iron_horse_armor",   display="Iron Horse Armor",   stack=1},
        {id=418, name="minecraft:golden_horse_armor", display="Golden Horse Armor", stack=1},
        {id=419, name="minecraft:diamond_horse_armor",display="Diamond Horse Armor",stack=1},
        {id=420, name="minecraft:lead",               display="Lead",               stack=64},
        {id=421, name="minecraft:name_tag",           display="Name Tag",           stack=64},
        {id=422, name="minecraft:prismarine_crystals",display="Prismarine Crystals",stack=64},
        {id=423, name="minecraft:mutton",             display="Raw Mutton",         stack=64, food=2},
        {id=424, name="minecraft:cooked_mutton",      display="Cooked Mutton",      stack=64, food=6},
        {id=425, name="minecraft:banner",             display="Black Banner",       stack=16},
        {id=426, name="minecraft:end_crystal",        display="End Crystal",        stack=64},
        {id=427, name="minecraft:spruce_door",        display="Spruce Door",        stack=64},
        {id=428, name="minecraft:birch_door",         display="Birch Door",         stack=64},
        {id=429, name="minecraft:jungle_door",        display="Jungle Door",        stack=64},
        {id=430, name="minecraft:acacia_door",        display="Acacia Door",        stack=64},
        {id=431, name="minecraft:dark_oak_door",      display="Dark Oak Door",      stack=64},
        {id=432, name="minecraft:chorus_fruit",       display="Chorus Fruit",       stack=64, food=4},
        {id=433, name="minecraft:popped_chorus_fruit",display="Popped Chorus Fruit",stack=64},
        {id=434, name="minecraft:banner_pattern",     display="Banner Pattern",     stack=1},
        {id=437, name="minecraft:dragon_breath",      display="Dragon's Breath",    stack=64},
        {id=438, name="minecraft:splash_potion",      display="Splash Potion",      stack=1},
        {id=441, name="minecraft:lingering_potion",   display="Lingering Potion",   stack=1},
        {id=442, name="minecraft:shield",             display="Shield",             stack=1,  durability=336},
        {id=443, name="minecraft:elytra",             display="Elytra",             stack=1,  durability=431},
        {id=444, name="minecraft:spruce_boat",        display="Spruce Boat",        stack=1},
        {id=445, name="minecraft:birch_boat",         display="Birch Boat",         stack=1},
        {id=446, name="minecraft:jungle_boat",        display="Jungle Boat",        stack=1},
        {id=447, name="minecraft:acacia_boat",        display="Acacia Boat",        stack=1},
        {id=448, name="minecraft:dark_oak_boat",      display="Dark Oak Boat",      stack=1},
        {id=449, name="minecraft:totem_of_undying",   display="Totem of Undying",   stack=1},
        {id=450, name="minecraft:shulker_shell",      display="Shulker Shell",      stack=64},
        {id=452, name="minecraft:iron_nugget",        display="Iron Nugget",        stack=64},
        {id=453, name="minecraft:music_disc_13",      display="Music Disc",         stack=1},
        {id=454, name="minecraft:music_disc_cat",     display="Music Disc Cat",     stack=1},
        -- 1.16 items
        {id=523, name="minecraft:netherite_ingot",    display="Netherite Ingot",    stack=64},
        {id=524, name="minecraft:netherite_sword",    display="Netherite Sword",    stack=1,  durability=2031},
        {id=525, name="minecraft:netherite_shovel",   display="Netherite Shovel",   stack=1,  durability=2031},
        {id=526, name="minecraft:netherite_pickaxe",  display="Netherite Pickaxe",  stack=1,  durability=2031},
        {id=527, name="minecraft:netherite_axe",      display="Netherite Axe",      stack=1,  durability=2031},
        {id=528, name="minecraft:netherite_hoe",      display="Netherite Hoe",      stack=1,  durability=2031},
        {id=529, name="minecraft:netherite_helmet",   display="Netherite Helmet",   stack=1,  durability=407,  armor=3},
        {id=530, name="minecraft:netherite_chestplate",display="Netherite Chestplate",stack=1,durability=592, armor=8},
        {id=531, name="minecraft:netherite_leggings", display="Netherite Leggings", stack=1,  durability=555, armor=6},
        {id=532, name="minecraft:netherite_boots",    display="Netherite Boots",    stack=1,  durability=481, armor=3},
        {id=533, name="minecraft:netherite_scrap",    display="Netherite Scrap",    stack=64},
        {id=534, name="minecraft:crimson_sign",       display="Crimson Sign",       stack=16},
        {id=535, name="minecraft:warped_sign",        display="Warped Sign",        stack=16},
        -- 1.17 items
        {id=590, name="minecraft:raw_iron",           display="Raw Iron",           stack=64},
        {id=591, name="minecraft:raw_gold",           display="Raw Gold",           stack=64},
        {id=592, name="minecraft:raw_copper",         display="Raw Copper",         stack=64},
        {id=593, name="minecraft:copper_ingot",       display="Copper Ingot",       stack=64},
        {id=594, name="minecraft:amethyst_shard",     display="Amethyst Shard",     stack=64},
        {id=595, name="minecraft:spyglass",           display="Spyglass",           stack=1},
        {id=596, name="minecraft:tinted_glass",       display="Tinted Glass",       stack=64},
        {id=597, name="minecraft:bundle",             display="Bundle",             stack=1},
        {id=598, name="minecraft:glow_ink_sac",       display="Glow Ink Sac",       stack=64},
        {id=599, name="minecraft:glow_berries",       display="Glow Berries",       stack=64, food=2},
        -- 1.19 items
        {id=620, name="minecraft:echo_shard",         display="Echo Shard",         stack=64},
        {id=621, name="minecraft:disc_fragment_5",    display="Disc Fragment",      stack=64},
        {id=622, name="minecraft:recovery_compass",   display="Recovery Compass",   stack=1},
        {id=623, name="minecraft:goat_horn",          display="Goat Horn",          stack=1},
        {id=624, name="minecraft:mangrove_boat",      display="Mangrove Boat",      stack=1},
        {id=625, name="minecraft:tadpole_bucket",     display="Bucket of Tadpole",  stack=1},
        -- 1.20 items
        {id=650, name="minecraft:bamboo_chest_raft",  display="Bamboo Chest Raft",  stack=1},
        {id=651, name="minecraft:cherry_boat",        display="Cherry Boat",        stack=1},
        {id=652, name="minecraft:brush",              display="Brush",              stack=1,  durability=64},
        {id=653, name="minecraft:pottery_shard_archer",display="Pottery Sherd",     stack=64},
        {id=654, name="minecraft:netherite_upgrade_smithing_template",display="Netherite Upgrade",stack=1},
        -- 1.21 items
        {id=680, name="minecraft:wind_charge",        display="Wind Charge",        stack=64},
        {id=681, name="minecraft:mace",               display="Mace",               stack=1,  durability=500},
        {id=682, name="minecraft:trial_key",          display="Trial Key",          stack=64},
        {id=683, name="minecraft:ominous_trial_key",  display="Ominous Trial Key",  stack=64},
        {id=684, name="minecraft:ominous_bottle",     display="Ominous Bottle",     stack=64},
        {id=685, name="minecraft:armadillo_scute",    display="Armadillo Scute",    stack=64},
        {id=686, name="minecraft:wolf_armor",         display="Wolf Armor",         stack=1,  durability=64},
        {id=687, name="minecraft:breeze_rod",         display="Breeze Rod",         stack=64},
        {id=688, name="minecraft:flow_armor_trim_smithing_template",display="Flow Armor Trim",stack=1},
    }
    for _, item in ipairs(list) do self:register(item) end
end

return setmetatable(ItemRegistry, {
    __call = function(cls) return cls.getInstance() end,
    __index = function(cls, k) return cls.getInstance()[k] end,
})
